<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="3"
            failures="1"
            tests="2">

  <testsuite name="login.spec"
    errors="3" failures="1" hostname="" id="" package="login.spec" skipped="1"
    tests="2" time="3.216" timestamp="Fri, 28 Apr 2017 10:26:27 GMT">
  
    <testcase name="Login Users" classname="login.spec" time="3.216" assertions="2">
<system-out>[[ATTACHMENT|/Users/chineduofor/Documents/Work/checkpoint 2/Document-Management-System/screenshots/login.spec/Login-Users_ERROR_Apr-28-2017-112628-GMT+0100.png]][[ATTACHMENT|/Users/chineduofor/Documents/Work/checkpoint 2/Document-Management-System/screenshots/login.spec/Login-Users_ERROR_Apr-28-2017-112628-GMT+0100.png]][[ATTACHMENT|/Users/chineduofor/Documents/Work/checkpoint 2/Document-Management-System/screenshots/login.spec/Login-Users_ERROR_Apr-28-2017-112629-GMT+0100.png]]</system-out>
      <failure message="Testing if the URL equals &quot;http://localhost:8080/app/document&quot;.">    at Object.LoginUsers [as Login Users] (/Users/chineduofor/Documents/Work/checkpoint 2/Document-Management-System/client/src/test/e2e/login.spec.js:13:15)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)</failure>

    
    </testcase>
  
  
    
    <testcase
      name="Invalid user" classname="login.spec">
      <skipped />
    </testcase>
    
  
  </testsuite>
</testsuites>
